### ISSUE TITLE
Importing grequests after requests breaks requests

### ISSUE THREAD

**Issue by cauebs** [spyoungtech/grequests#103]
```
>>> import requests
>>> import grequests
>>> requests.get('https://google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/util/ssl_.py", line 264, in create_urllib3_context
    context.options |= options
  File "/usr/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 323 more times]
RecursionError: maximum recursion depth exceeded
```

If the order of imports is reversed, the problem no longer occurs.

**Comment by ParseThis** [comment]
bump: seeing this as well. related : https://github.com/gevent/gevent/issues/903,

**Comment by sammymax** [comment]
Bump; also seeing this. As the traceback suggests, it seems to only be a problem with https sites.

**Comment by matan-carbonnv** [comment]
Seeing this too, got rid of it with 
```
def stub(*args, **kwargs):  # pylint: disable=unused-argument
    pass
monkey.patch_all = stub
import grequests
```

Anyone has a better workaround?

**Comment by wolfsif** [comment]
Same issue here.

**Comment by spyoungtech** [comment]
Ran into the same issue today. Thanks for reporting this issue or I would have been pulling my hair out.

**Comment by Netherdrake** [comment]
Same issue here, grequests breaks `urllib3`.

**Comment by cauebs** [comment]
It appears to have been fixed, but how?

**Comment by syb0rg** [comment]
This was solved for me by importing `requests` **after** `grequests`.

**Comment by spyoungtech** [comment]
This is not necessarily an issue with grequests, so I'm going to close this issue for now.

See also: https://github.com/gevent/gevent/issues/1235

Also of note: gevent now emits a warning in this scenario when modules are imported before gevent has the opportunity to patch them.

**Comment by manna018** [comment]
I am getting error while initialising Azure Client 
My import looks like this:
```
from gevent import monkey as curious_george
curious_george.patch_all(thread=False, select=False)
import grequests
.
.

.
from azure.common.credentials import ServicePrincipalCredentials
```
Plz help
