### ISSUE TITLE
module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by flolep2607** [spyoungtech/grequests#141]
Python 3.7.5
`Traceback (most recent call last):
  File "other.py", line 1, in <module>
    import grequests, re
  File "C:\Users\flole\AppData\Local\Programs\Python\Python38-32\lib\site-packages\grequests.py", line 22, in <module>
    curious_george.patch_all(thread=False, select=False)
  File "C:\Users\flole\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gevent\monkey.py", line 1146, in patch_all
    from gevent import events
  File "C:\Users\flole\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gevent\events.py", line 91, in <module>
    __import__('pkg_resources')
  File "C:\Users\flole\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'`

**Comment by spyoungtech** [comment]
Hmm. Based on the traceback, it looks like you're actually using Python 3.8, not 3.7.5 -- perhaps something unexpected in your PATH/PYTHONPATH is causing this?

At any rate, one thing you can try is installing a different version of `gevent` and see if that helps. If not, let me know what version of gevent you have, the version of Python you're using and on what platform.

If you're using grequests with other packages that also use `gevent` that would also be good to know.

**Comment by spyoungtech** [comment]
Since I haven't heard back in a while, I'm going to close this issue as it doesn't seem like a problem with grequests.
