### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by latot** [spyoungtech/grequests#162]
Hi, yesterday I upgraded all python packages, and I notice I can't import grequests now D:

```
>>> import grequests
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3037, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2834, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pipe/.local/lib/python3.10/site-packages/grequests.py", line 22, in <module>
    curious_george.patch_all(thread=False, select=False)
  File "/home/pipe/.local/lib/python3.10/site-packages/gevent/monkey.py", line 1255, in patch_all
    _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/home/pipe/.local/lib/python3.10/site-packages/gevent/monkey.py", line 190, in _notify_patch
    notify_and_call_entry_points(event)
  File "/home/pipe/.local/lib/python3.10/site-packages/gevent/events.py", line 104, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2470, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2492, in require
    reqs = self.dist.requires(self.extras)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2755, in requires
    dm = self._dep_map
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3039, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3056, in _compute_dependencies
    common = types.MappingProxyType(dict.fromkeys(reqs_for_extra(None)))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3053, in reqs_for_extra
    if not req.marker or req.marker.evaluate({'extra': extra}):
  File "/home/pipe/.local/lib/python3.10/site-packages/packaging/markers.py", line 241, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/home/pipe/.local/lib/python3.10/site-packages/packaging/markers.py", line 150, in _evaluate_markers
    lhs_value, rhs_value = _normalize(lhs_value, rhs_value, key=environment_key)
  File "/home/pipe/.local/lib/python3.10/site-packages/packaging/markers.py", line 124, in _normalize
    return tuple(canonicalize_name(v) for v in values)
  File "/home/pipe/.local/lib/python3.10/site-packages/packaging/markers.py", line 124, in <genexpr>
    return tuple(canonicalize_name(v) for v in values)
  File "/home/pipe/.local/lib/python3.10/site-packages/packaging/utils.py", line 34, in canonicalize_name
    value = _canonicalize_regex.sub("-", name).lower()
TypeError: expected string or bytes-like object
```

Thx!

**Comment by latot** [comment]
no idea why, in linux, remove the ~/.local/lib/python-3.10, install all again and now works fine.
